inv/urls.py
from django.urls import path

from .views import IngredienteView, IngredienteNew, IngredienteEdit, IngredienteDel, ProductoView, ProductoNew, ProductoEdit, ProductoDel

urlpatterns = [
    path('ingredientes/',IngredienteView.as_view(), name='ingrediente_list'),
    path('ingredientes/new',IngredienteNew.as_view(), name='ingrediente_new'),
    path('ingredientes/edit/<int:pk>',IngredienteEdit.as_view(), name='ingrediente_edit'),
    path('ingredientes/delate/<int:pk>',IngredienteDel.as_view(), name='ingrediente_del'),
    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delate/<int:pk>',ProductoDel.as_view(), name='producto_del'),
]

pizzeriadoo/inv/urls.py
from django.urls import path

from .views import IngredienteView, IngredienteNew, IngredienteEdit, IngredienteDel, ProductoView, ProductoNew, ProductoEdit, ProductoDel

urlpatterns = [
    path('ingredientes/',IngredienteView.as_view(), name='ingrediente_list'),
    path('ingredientes/new',IngredienteNew.as_view(), name='ingrediente_new'),
    path('ingredientes/edit/<int:pk>',IngredienteEdit.as_view(), name='ingrediente_edit'),
    path('ingredientes/delate/<int:pk>',IngredienteDel.as_view(), name='ingrediente_del'),
    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delate/<int:pk>',ProductoDel.as_view(), name='producto_del'),
]

pizzeriadoo/pizzeriadoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

renombraLaCarpetaComopizzeriadoo/inv/urls.py
from django.urls import path

from .views import IngredienteView, IngredienteNew, IngredienteEdit, IngredienteDel, ProductoView, ProductoNew, ProductoEdit, ProductoDel

urlpatterns = [
    path('ingredientes/',IngredienteView.as_view(), name='ingrediente_list'),
    path('ingredientes/new',IngredienteNew.as_view(), name='ingrediente_new'),
    path('ingredientes/edit/<int:pk>',IngredienteEdit.as_view(), name='ingrediente_edit'),
    path('ingredientes/delate/<int:pk>',IngredienteDel.as_view(), name='ingrediente_del'),
    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delate/<int:pk>',ProductoDel.as_view(), name='producto_del'),
]

AAAAAAAAAAAA/pizzeriadoo/inv/models.py
from django.db import models

from bases.models import ClaseModelo

class Ingrediente(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción del Ingrediente',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Ingrediente, self).save()

    class Meta:
        verbose_name_plural= "Ingredientes"

class Producto(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción del Producto',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural= "Productos"

bases/models.py
from django.db import models
from django.contrib.auth.models import User

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)
    

    class Meta:
        abstract = True

AAAAAAAAAAAA/pizzeriadoo/inv/forms.py
from django import forms

from .models import Ingrediente, Producto


class IngredienteForm(forms.ModelForm):
    class Meta:
        model=Ingrediente
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción del Ingrediente",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripción del Producto",
               "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

AAAAAAAAAAAA/pizzeriadoo/inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import Ingrediente, Producto
from .forms import IngredienteForm, ProductoForm
#from .forms import Categreverse.lazy


class IngredienteView(LoginRequiredMixin, generic.ListView):
    model = Ingrediente
    template_name = "inv/ingrediente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class IngredienteNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class IngredienteEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class IngredienteDel(LoginRequiredMixin,generic.DeleteView):
    model=Ingrediente
    template_name='inv/ingredientes_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:ingrediente_list")

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDel(LoginRequiredMixin,generic.DeleteView):
    model=Producto
    template_name='inv/productos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:producto_list")

inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import Ingrediente, Producto
from .forms import IngredienteForm, ProductoForm
#from .forms import Categreverse.lazy


class IngredienteView(LoginRequiredMixin, generic.ListView):
    model = Ingrediente
    template_name = "inv/ingrediente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class IngredienteNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class IngredienteEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class IngredienteDel(LoginRequiredMixin,generic.DeleteView):
    model=Ingrediente
    template_name='inv/ingredientes_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:ingrediente_list")

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDel(LoginRequiredMixin,generic.DeleteView):
    model=Producto
    template_name='inv/productos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:producto_list")

pizzeriadoo/inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import Ingrediente, Producto
from .forms import IngredienteForm, ProductoForm
#from .forms import Categreverse.lazy


class IngredienteView(LoginRequiredMixin, generic.ListView):
    model = Ingrediente
    template_name = "inv/ingrediente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class IngredienteNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class IngredienteEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class IngredienteDel(LoginRequiredMixin,generic.DeleteView):
    model=Ingrediente
    template_name='inv/ingredientes_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:ingrediente_list")

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDel(LoginRequiredMixin,generic.DeleteView):
    model=Producto
    template_name='inv/productos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:producto_list")

renombraLaCarpetaComopizzeriadoo/inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import Ingrediente, Producto
from .forms import IngredienteForm, ProductoForm
#from .forms import Categreverse.lazy


class IngredienteView(LoginRequiredMixin, generic.ListView):
    model = Ingrediente
    template_name = "inv/ingrediente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class IngredienteNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class IngredienteEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Ingrediente
    template_name="inv/ingrediente_form.html"
    context_object_name = "obj"
    form_class=IngredienteForm
    success_url=reverse_lazy("inv:ingrediente_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class IngredienteDel(LoginRequiredMixin,generic.DeleteView):
    model=Ingrediente
    template_name='inv/ingredientes_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:ingrediente_list")

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    #permission_required="inv.view_Ingrediente"

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    #permission_required="inv.add_ingrediente" 
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url='bases:login'
 

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDel(LoginRequiredMixin,generic.DeleteView):
    model=Producto
    template_name='inv/productos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:producto_list")

pizzeriadoo/inv/templates/inv/ingrediente_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              {% if obj %} Editar {% else %} Nuevo {% endif %} Ingrediente
            </div>
            <div class="dropdownn-divider"></div>
            <div class="row">
              <div class="col-10">
                <div class="input-group">
                  <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                </div>
              </div>
              <div class="col-2">
                <div class="form-group">
                  <label for="id_estado">Estado</label>
                  <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}>
                </div>
              </div>
            </div>
            <!-- {{ form.as_p }} -->
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>Guardar</button>
                <a href="{% url 'inv:ingrediente_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

pizzeriadoo/inv/templates/inv/ingrediente_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Ingredientes</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:ingrediente_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
          <a class="dropdown-item" href="#">Another action</a> 
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Ingredientes</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Id</th>
              <th>Descripción</th>
              <th>Estado</th>
              <th>Fecha Creado</th>
              <th>Fecha Modificado</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <!--
                    Le quité otra parte de codigo para que funcionara, está enviado a Leo en un mensaje a las 
                    03:54am del 01/12/20
                    No se porque no funciona pero el error diceque no se encuentra el ingrediente_list.html, al quitarlo
                    dice lo mismo de ingrediente_del.html
                  -->
                  <td>
                    <a href="{% url 'inv:ingrediente_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> 
                    <a href="{% url 'inv:ingrediente_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>

              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

pizzeriadoo/inv/templates/inv/ingredientes_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{ obj.descripcion }}?</div>
                      <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Sis</button>
                      <a href="{% url 'inv:ingrediente_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Non</a>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

pizzeriadoo/inv/templates/inv/producto_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              {% if obj %} Editar {% else %} Nuevo {% endif %} Producto
            </div>
            <div class="dropdownn-divider"></div>
            <div class="row">
              <div class="col-10">
                <div class="input-group">
                  <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                </div>
              </div>
              <div class="col-2">
                <div class="form-group">
                  <label for="id_estado">Estado</label>
                  <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}>
                </div> 
              </div>
            </div>
            <!-- {{ form.as_p }} -->
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>Guardar</button>
                <a href="{% url 'inv:producto_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

pizzeriadoo/inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:producto_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
          <a class="dropdown-item" href="#">Another action</a> 
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Productos</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Id</th>
              <th>Descripción</th>
              <th>Estado</th>
              <th>Creado</th>
              <th>Fecha Modif</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <td>
                    <a href="{% url 'inv:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> 
                    <a href="{% url 'inv:producto_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>

              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

pizzeriadoo/inv/templates/inv/productos_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{ obj.descripcion }}?</div>
                      <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Sis </button>
                      <a href="{% url 'inv:producto_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Non </a>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}