AAAAAAAAAAAA/pizzeriadoo/pizzeriadoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from bases.views import Home

urlpatterns =  [
    path('', Home.as_view(), name='base'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

inv/urls.py
from django.urls import path

from .views import IngredienteView, IngredienteNew, IngredienteEdit, IngredienteDel, ProductoView, ProductoNew, ProductoEdit, ProductoDel

urlpatterns = [
    path('ingredientes/',IngredienteView.as_view(), name='ingrediente_list'),
    path('ingredientes/new',IngredienteNew.as_view(), name='ingrediente_new'),
    path('ingredientes/edit/<int:pk>',IngredienteEdit.as_view(), name='ingrediente_edit'),
    path('ingredientes/delate/<int:pk>',IngredienteDel.as_view(), name='ingrediente_del'),
    path('productos/',ProductoView.as_view(), name='producto_list'),
    path('productos/new',ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delate/<int:pk>',ProductoDel.as_view(), name='producto_del'),
]

pizzeriadoo/pizzeriadoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

renombraLaCarpetaComopizzeriadoo/pizzeriadoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PIZZERIADOO</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template--> 
    <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- jQuery confirm -->
    <link href="{% static 'base/vendor/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}" rel="stylesheet">

</head>

<body id="page-top" class="bg-gradient-primary">
    {% block side_bar %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand 
                Tambien me da error al quitar la parte de index y agregar el {url bases:home}
                Se que está mal escrito en este comentario

                AAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaAAAaaaa
                Otro error que se tiene, es que en este punto al no estar logeado y tratar de entrar mediante el URL
                inv/ingredientes/ debería de redireccionar a la pagina de login.
                Pero lo anterior no lo hace ._.XD
            -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">PIZZERIADOO</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard 
                Se quitó el dashboard porque estaba quenerando un error, el cual no se sabe la razón.
                A
                - Diana
            -->


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Opciones del Menú
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Catalogo de Inventraio</h6>
                        <a class="collapse-item" href="{% url 'inv:ingrediente_list' %}">Ingredientes</a>
                        <a class="collapse-item" href="{% url 'inv:producto_list' %}">Productos</a>
                    </div>
                </div>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        {% endblock side_bar %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% block top_bar %}
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <h1 style="text-align:center">PIZZERIADOO</h1>
                            <div class="input-group-append">
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                   


                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Administrador</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'base/img/korone.jpg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                               
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                {% endblock top_bar %}
                <!-- End of Topbar -->

                {% block page_content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800" style="text-align:center">INFORMACIÓN GENERAL</h1>
                    
                               <p><img src="{% static 'base/img/p.png' %}" style="float:right"> <h3>MATERIA:</h3>
                                        <h6>Analisis y Diseño Orientado a Objetos</h6>
                            

                                <h3>INTEGRANTES</h3>
                                <ul>
                                    <li>Diana Jaqueline Bonilla Sánchez</li>
                                    <li>José Leonardo Rafael Calderon Gallegos</li>
                                    <li>Jesús Galván Esquivel</li>
                                    <li>Javier Muro Cervantes</li>
                                    <li>Javier Delgado Vargas</li>
                                    <li>Joel Salas Moreno</li>
                                    <li>Jesús Emmanuel Ibarra Cruz</li>
                                </ul> 
                                </p>


                </div>
                {% endblock page_content %}
                <!-- /.container-fluid -->

            {% block footer%}
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    {% endblock footer %}

    <!-- End of Page Wrapper -->
    {% block login%} {% endblock login %}
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'bases:logout' %}">Salir</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    {% block js_page %} {% endblock js_page %}

</body>

</html>